# Section 4. N차원 배열 정렬

### 4-1. 1차원 배열의 정렬

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(10, size = 10)
print(arr)

[1 0 6 0 1 6 8 5 8 1]


In [4]:
print(np.sort(arr))
print(np.sort(arr)[::-1]) # [::] : 처음부터 끝까지

[0 0 1 1 1 5 6 6 8 8]
[8 8 6 6 5 1 1 1 0 0]


In [5]:
arr.sort()
print(arr)

[0 0 1 1 1 5 6 6 8 8]


### 4-2. 2차원 배열의 정렬

In [6]:
arr = np.random.randint(15, size=(3, 4))
print(arr)

[[ 2  2 10 14]
 [10 13  1 10]
 [ 7 11  4 11]]


In [10]:
print(np.sort(arr, axis=None))

[ 1  2  2  4  7 10 10 10 11 11 13 14]


In [12]:
# argsort()
print(np.sort(arr, axis = 0))
print(np.argsort(arr, axis = 0))

[[ 2  2  1 10]
 [ 7 11  4 11]
 [10 13 10 14]]
[[0 0 1 1]
 [2 2 2 2]
 [1 1 0 0]]
