# Section 5. N차원 배열의 형태 변경

### 5-1. 배열의 형태 변경1 : reshape()

In [2]:
import numpy as np

In [6]:
arr = np.arange(12)
print(arr, arr.ndim)

arr = arr.reshape((3, 4))
print(arr, arr.ndim)

arr = arr.reshape((2, 3, 2))
print(arr, arr.ndim)

arr = arr.reshape((2, 2, 1, 3))
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


### 5-1. 배열의 형태 변경2 : resize(), ravel()

In [7]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
arr.resize(3, 4)
print(arr)

arr = arr.ravel()
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
arr = np.arange(1, 13)
print(arr)

arr = arr.reshape(3, -1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
