# Section 3. N차원 배열 연산법

### 3-1. 배열의 연산1 : 사칙연산/제곱/제곱근/몫/나머지

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.array([[2, 2, 2],
                 [2, 2, 2],
                 [2, 2, 2]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [4]:
# 덧셈
print(arr1 + arr2)
print(np.add(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
# 뺄셈
print(arr1 - arr2)
print(np.subtract(arr1, arr2))

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [6]:
# 곱셈
print(arr1 * arr2)
print(np.multiply(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [7]:
# 나눗셈
print(arr1 / arr2)
print(np.divide(arr1, arr2))

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [9]:
# 제곱
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.array([[2, 2, 2],
                 [2, 2, 2],
                 [2, 2, 2]])

print(arr1 ** 5)
print(np.square(arr1))

# 제곱근
print(np.sqrt(arr1))

[[    1    32   243]
 [ 1024  3125  7776]
 [16807 32768 59049]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [10]:
# 몫
print(arr1 // 2)

# 나머지
print(arr1 % 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


### 3-2. 배열의 연산2 : 내적(dot product)/절댓값/올림/내림/반올림/버림

#### =두 벡터, 즉, 두 행렬을 곱했을 때 그 값이 스칼라 값이 나오는 경우

In [11]:
# 1차원 행렬
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])

print(np.dot(arr1, arr2))

20


In [12]:
# 2차원 행렬
'''
[[a, b]  [e, f]     [[ae + bg, af + bh]
 [c, d]   [g, h]] => [ce + df, cf + dh]]
'''

arr1 = np.array([[1, 2],
                 [4, 5]])
arr2 = np.array([[1, 2],
                 [0, 3]])
print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


In [13]:
# 절댓값
arr1 = np.array([[1, -2],
                 [-4, 5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [17]:
# 올림
arr1 = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])
print(np.ceil(arr1))

# 내림
print(np.floor(arr1))

# 반올림
print(np.round(arr1))

# 버림
print(np.trunc(arr1))

[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]


### 3-3. 배열의 연산3 : min/max/sum/mean/std/cumsum/median

In [18]:
arr = np.array([[1, 2, 3],
                [0, 1, 4]])

In [22]:
# min()
print(np.min(arr))
print(arr.min())
print(arr.min(axis=1))

0
0
[1 0]


In [23]:
# max()
print(np.max(arr))
print(arr.max(axis=1))

4
[3 4]


In [26]:
# sum()
print(np.sum(arr))
print(arr.sum(axis=1))

# mean()
print(np.mean(arr))
print(arr.mean(axis=1))

11
[6 5]
1.8333333333333333
[2.         1.66666667]


In [32]:
# std()
print(np.std(arr))
print(arr.std(axis=0))

# cumsum()
print(np.cumsum(arr))
print(arr.cumsum())
print(arr.cumsum(axis=0))

1.343709624716425
[0.5 0.5 0.5]
[ 1  3  6  6  7 11]
[ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]]


In [34]:
arr = np.array([[1, 2, 3],
                [0, 1, 4],
                [1, 5, 2]])

In [37]:
# median()
print(np.median(arr, axis=1))

[2. 1. 2.]


### 3-4. 배열의 연산4 : 비교 연산 / 삼각함수 

In [39]:
# 비교 연산
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1, 0, 3],
                 [4, -2, 9]])
print(arr1 == arr2)
print(arr1 > arr2)
print(np.array_equal(arr1, arr2)) #배열 전체가 동일한지 알아보는 방법

[[ True False  True]
 [ True False False]]
[[False  True False]
 [False  True False]]
False


In [41]:
# 삼각함수
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# sin()
print(np.sin(arr))

# cos()
print(np.cos(arr))

# tan()
print(np.tan(arr))

# pi
print(np.pi)

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
3.141592653589793


### 3-5. 브로드캐스팅(Broadcasting)

In [42]:
arr1 = np.array([[0, 0, 0],
                 [1, 1, 1],
                 [2, 2, 2]])
arr2 = np.array([[5, 6 ,7]])

print(arr1 + arr2)

arr1 = np.array([[1 ,1 ,1]])
arr2 = np.array([1])

print(arr1 + arr2)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[2 2 2]]


### 3-6. 벡터 연산의 장점

In [43]:
import time

In [45]:
arr = np.arange(99999999)

In [47]:
# for
sum = 0;
before = time.time()
for i in arr:
    sum += i
after = time.time()
print(sum, after - before, "초")

4999999850000001 20.94869303703308 초


In [49]:
# 벡터 연산
before = time.time()
sum = np.sum(arr)
after = time.time()
print(sum, after - before, "초")

4999999850000001 0.07559394836425781 초


In [51]:
arr1 = np.arange(99999999)
arr2 = np.arange(99999999)

In [54]:
# for
sum = 0
before = time.time()
for i, j in zip(arr1, arr2): # zip() 경우 갯수가 동일한 sequential 자리에만 사용가능
    sum += i * j
after = time.time()
print(sum, after - before, "초")

/Users/otaehun/opt/anaconda3/envs/test1/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in long_scalars
  """


652921401952298879 40.18451404571533 초


In [55]:
# 벡터 연산
before = time.time()
sum = np.dot(arr1, arr2)
after = time.time()
print(sum, after = before, "초")

SyntaxError: positional argument follows keyword argument (3004387475.py, line 5)